#!/bin/bash

# Enable ipywidgets extension
jupyter nbextension enable --py widgetsnbextension --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager

# Enable voila
jupyter serverextension enable voila --sys-prefix

# If you have FreeSurfer data, uncomment and adjust:
# mkdir -p data/fs_subjects
# wget -O data.zip YOUR_DATA_URL
# unzip data.zip -d data/
pip install -e .
